### ISSUE TITLE
Add twilio to requirements.txt

### ISSUE THREAD

**Issue by osteele** [aidankmcl/futureboard#10]
```
$ pip install -r requirements.txt
$ python -m app.server
Traceback (most recent call last):
  File "/Users/osteele/anaconda3/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/osteele/anaconda3/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/osteele/code/htl/futureboard/app/server.py", line 27, in <module>
    from twilio.rest import Client
ImportError: No module named 'twilio'
```

Actually, how does the Heroku deployment manage to work without this?

**Comment by aidankmcl** [comment]
Gotcha!
